name: depaware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v3

    - name: depaware
      run: go run github.com/tailscale/depaware --check
        tailscale.com/cmd/tailscaled
        tailscale.com/cmd/tailscale
        tailscale.com/cmd/derper
